#node version 18.18
# base image
FROM node:18.18-alpine
# 
WORKDIR /app
#
COPY package*.json ./
# install modules
RUN npm install
# copy source code
COPY . .

# build
RUN npm run build

# port opens
EXPOSE 3000

# start 
CMD [ "npm" , "start"]